/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jagobo (https://sketchfab.com/Jagobo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tropical-mango-trees-free-6997814540f14929bf13cf3828b5dc90
Title: Tropical Mango Trees Free
*/
import { ThreeElements } from "@react-three/fiber";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type GLTFResult = {
  nodes: {
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_37: THREE.Mesh;
  };
  materials: {
    foliage: THREE.Material;
    bark: THREE.Material;
    fruit: THREE.Material;
  };
};

export function Trees(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/tropical_mango_trees_free.glb",
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, 23.494]}
        rotation={[Math.PI / 4, 0, 2.689]}
        scale={0.101}
      >
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.foliage}
        /> */}
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.foliage}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.foliage}
        /> */}
      </group>
      {/* <group
        position={[0, 0, -31.183]}
        rotation={[Math.PI / 2, 0, -0.994]}
        scale={0.168}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.foliage}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials.foliage}
        />
      </group> */}
      <group
        position={[0, 0, -74.156]}
        rotation={[Math.PI / 2, 0, 1.473]}
        scale={0.252}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_33.geometry}
          material={materials.foliage}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials.foliage}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_35.geometry}
          material={materials.foliage}
        />
      </group>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.bark}
        position={[0, 0, 42.939]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.056}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.foliage}
        position={[0, 0, 42.939]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.fruit}
        position={[0, 0, 42.939]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.056}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.bark}
        position={[0, 0, 23.494]}
        rotation={[Math.PI / 2, 0, 2.689]}
        scale={0.101}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.fruit}
        position={[0, 0, 23.494]}
        rotation={[Math.PI / 2, 0, 2.689]}
        scale={0.101}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.bark}
        position={[0, 0, -0.132]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.13}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.foliage}
        position={[0, 0, -0.132]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.13}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.fruit}
        position={[0, 0, -0.132]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.13}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.bark}
        position={[0, 0, -31.183]}
        rotation={[Math.PI / 2, 0, -0.994]}
        scale={0.168}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials.fruit}
        position={[0, 0, -31.183]}
        rotation={[Math.PI / 2, 0, -0.994]}
        scale={0.168}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.bark}
        position={[0, 0, -74.156]}
        rotation={[Math.PI / 2, 0, 1.473]}
        scale={0.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials.fruit}
        position={[0, 0, -74.156]}
        rotation={[Math.PI / 2, 0, 1.473]}
        scale={0.252}
      />
    </group>
  );
}

useGLTF.preload("/tropical_mango_trees_free.glb");
