/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MozzarellaARC (https://sketchfab.com/mozzarellaARC)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tropical-plants-pack-m02p-2f093afb792742438f0f7ba7eaab90f0
Title: Tropical Plants Pack M02P
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import * as THREE from "three";

export type GLTFResult = {
  nodes: {
    SM_MZRa_Palm_B081_MI_MZRa_Palm_B08b_0: THREE.Mesh;
    SM_MZRa_Palm_B081_MI_MZRa_Palm_B08a_0: THREE.Mesh;
    SM_MZRa_Palm_B082_MI_MZRa_Palm_B08b_0: THREE.Mesh;
    SM_MZRa_Palm_B082_MI_MZRa_Palm_B08a_0: THREE.Mesh;
    SM_MZRa_Palm_B083_MI_MZRa_Palm_B08b_0: THREE.Mesh;
    SM_MZRa_Palm_B083_MI_MZRa_Palm_B08a_0: THREE.Mesh;
    SM_MZRa_Banana_B091_MI_MZRa_Banana_B09a_0: THREE.Mesh;
    SM_MZRa_Banana_B091_MI_MZRa_Banana_B09b_0: THREE.Mesh;
    SM_MZRa_Banana_B092_MI_MZRa_Banana_B09a_0: THREE.Mesh;
    SM_MZRa_Banana_B092_MI_MZRa_Banana_B09b_0: THREE.Mesh;
    tree007SM_MZRa_Monstera_B072_MI_MZRa_Monstera_B07b_0: THREE.Mesh;
    tree007SM_MZRa_Monstera_B072_MI_MZRa_Monstera_B07a1_0: THREE.Mesh;
    tree006SM_MZRa_Monstera_B071_MI_MZRa_Monstera_B07b_0: THREE.Mesh;
    tree006SM_MZRa_Monstera_B071_MI_MZRa_Monstera_B07a1_0: THREE.Mesh;
    tree006SM_MZRa_Monstera_B071_MI_MZRa_Monstera_B07a2_0: THREE.Mesh;
    tree003SM_MZRa_Monstera_B073_MI_MZRa_Monstera_B07b_0: THREE.Mesh;
    tree003SM_MZRa_Monstera_B073_MI_MZRa_Monstera_B07a1_0: THREE.Mesh;
    tree002SM_MZRa_Monstera_B074_MI_MZRa_Monstera_B07b_0: THREE.Mesh;
    tree002SM_MZRa_Monstera_B074_MI_MZRa_Monstera_B07a1_0: THREE.Mesh;
    SM_MZRa_Fern_B0532_MI_MZRa_Fern_B053_0: THREE.Mesh;
    SM_MZRa_Fern_B0512_MI_MZRa_Fern_B051_0: THREE.Mesh;
    SM_MZRa_Fern_B0522_MI_MZRa_Fern_B052_0: THREE.Mesh;
    SM_MZRa_Fern_B052_MI_MZRa_Fern_B052_0: THREE.Mesh;
    SM_MZRa_Fern_B053_MI_MZRa_Fern_B053_0: THREE.Mesh;
    SM_MZRa_Fern_B051_MI_MZRa_Fern_B051_0: THREE.Mesh;
    Circle_BG_01_0: THREE.Mesh;
  };
  materials: {
    MI_MZRa_Palm_B08b: THREE.Material;
    MI_MZRa_Palm_B08a: THREE.Material;
    MI_MZRa_Banana_B09a: THREE.Material;
    MI_MZRa_Banana_B09b: THREE.Material;
    MI_MZRa_Monstera_B07b: THREE.Material;
    MI_MZRa_Monstera_B07a1: THREE.Material;
    MI_MZRa_Monstera_B07a2: THREE.Material;
    MI_MZRa_Fern_B053: THREE.Material;
    MI_MZRa_Fern_B051: THREE.Material;
    MI_MZRa_Fern_B052: THREE.Material;
    BG_01: THREE.Material;
  };
};

export function TropicalPlants(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/tropical_plants.glb",
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[220.416, 0, 110.125]} scale={0.817}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Palm_B081_MI_MZRa_Palm_B08b_0.geometry}
            material={materials.MI_MZRa_Palm_B08b}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Palm_B081_MI_MZRa_Palm_B08a_0.geometry}
            material={materials.MI_MZRa_Palm_B08a}
          />
        </group>
        <group
          position={[40.83, 0, -60.748]}
          rotation={[0, 0.438, 0]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Palm_B082_MI_MZRa_Palm_B08b_0.geometry}
            material={materials.MI_MZRa_Palm_B08b}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Palm_B082_MI_MZRa_Palm_B08a_0.geometry}
            material={materials.MI_MZRa_Palm_B08a}
          />
        </group>
        <group position={[-159.742, 0, 108.622]} scale={0.817}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Palm_B083_MI_MZRa_Palm_B08b_0.geometry}
            material={materials.MI_MZRa_Palm_B08b}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Palm_B083_MI_MZRa_Palm_B08a_0.geometry}
            material={materials.MI_MZRa_Palm_B08a}
          />
        </group>
        <group position={[-55.28, 0, 103.023]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Banana_B091_MI_MZRa_Banana_B09a_0.geometry}
            material={materials.MI_MZRa_Banana_B09a}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Banana_B091_MI_MZRa_Banana_B09b_0.geometry}
            material={materials.MI_MZRa_Banana_B09b}
          />
        </group>
        <group position={[133.979, 0, 177.75]} rotation={[0, 1.523, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Banana_B092_MI_MZRa_Banana_B09a_0.geometry}
            material={materials.MI_MZRa_Banana_B09a}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_MZRa_Banana_B092_MI_MZRa_Banana_B09b_0.geometry}
            material={materials.MI_MZRa_Banana_B09b}
          />
        </group>
        <group position={[-50.347, 0, 38.803]} scale={2.291}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree007SM_MZRa_Monstera_B072_MI_MZRa_Monstera_B07b_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07b}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree007SM_MZRa_Monstera_B072_MI_MZRa_Monstera_B07a1_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07a1}
          />
        </group>
        <group position={[-283.639, 0, 242.515]} scale={2.672}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree006SM_MZRa_Monstera_B071_MI_MZRa_Monstera_B07b_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07b}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree006SM_MZRa_Monstera_B071_MI_MZRa_Monstera_B07a1_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07a1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree006SM_MZRa_Monstera_B071_MI_MZRa_Monstera_B07a2_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07a2}
          />
        </group>
        <group
          position={[130.334, 0, 15.529]}
          rotation={[0, -0.565, 0]}
          scale={2.291}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree003SM_MZRa_Monstera_B073_MI_MZRa_Monstera_B07b_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07b}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree003SM_MZRa_Monstera_B073_MI_MZRa_Monstera_B07a1_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07a1}
          />
        </group>
        <group
          position={[384.157, 0, 230.651]}
          rotation={[0, -0.733, 0]}
          scale={2.291}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree002SM_MZRa_Monstera_B074_MI_MZRa_Monstera_B07b_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07b}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.tree002SM_MZRa_Monstera_B074_MI_MZRa_Monstera_B07a1_0
                .geometry
            }
            material={materials.MI_MZRa_Monstera_B07a1}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_MZRa_Fern_B0532_MI_MZRa_Fern_B053_0.geometry}
          material={materials.MI_MZRa_Fern_B053}
          position={[178.888, 0, 339.878]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_MZRa_Fern_B0512_MI_MZRa_Fern_B051_0.geometry}
          material={materials.MI_MZRa_Fern_B051}
          position={[-99.856, 0, 343.164]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_MZRa_Fern_B0522_MI_MZRa_Fern_B052_0.geometry}
          material={materials.MI_MZRa_Fern_B052}
          position={[43.529, 0, 393.248]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_MZRa_Fern_B052_MI_MZRa_Fern_B052_0.geometry}
          material={materials.MI_MZRa_Fern_B052}
          position={[36.595, 0, 271.824]}
          scale={2.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_MZRa_Fern_B053_MI_MZRa_Fern_B053_0.geometry}
          material={materials.MI_MZRa_Fern_B053}
          position={[219.161, 0, 234.32]}
          scale={2.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_MZRa_Fern_B051_MI_MZRa_Fern_B051_0.geometry}
          material={materials.MI_MZRa_Fern_B051}
          position={[-154.388, 0, 232.092]}
          scale={2.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_BG_01_0.geometry}
          material={materials.BG_01}
          position={[49.129, 0, -159.984]}
          scale={405.178}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/tropical_plants.glb");
